Host-Name=MacBookPro.local
Architecture=arm64
OS=macOS-27.0
Python=3.14.3
Browser=Chromium
Headless=False
Slow-Mo=500 ms
Base-URL=https://www.1minreport.com/
Test-User-Email=test.user@email.com
Test-User-Username=test-Username
Test-User-Password=test-Password_123